### ISSUE TITLE
[Bug] Missing Reader Menu when used with Better BibTeX

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-actions-tags#231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.54+6b996d4f9 (64-bit)
- Plugin Version: 1.0.0-31
- BBT Version: [v6.7.140](https://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.140)

### Describe the bug

Steps to reproduce with the A&T and BBT plugins:
1) Open a PDF file in a Zotero PDF Viewer
2) While looking at the PDF, close and restart Zotero

-> After restarting, the PDF Viewer loads automatically. But the Reader Menu of the plugin is missing.
Closing and reopening the tab fixes the problem, with the Reader Menu appearing again.
Doing the same with the BBT plugin disabled does not produce this issue.

### Debug Output

1704295785999	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1704295787417	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "NotFoundError: Could not get children of file(C:\Users\mjthoraval\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12

appName => Zotero, version => 7.0.0-beta.54+6b996d4f9, os => Windows 10.0 19045, locale => en-US, extensions => Better BibTex for Zotero (6.7.140, extension), Actions and Tags for Zotero (1.0.0-31, extension), Zotero PDF Preview (1.0.0-4, extension, disabled), Zotero Better Authors (4.0.2, extension, disabled), Translate for Zotero (1.1.0-22, extension, disabled), Better Notes for Zotero (1.1.4-49, extension, disabled), Open PDF for Zotero (0.0.10, extension, disabled)

**Comment by windingwind** [comment]
Could you please report this to the BBT repo as well? Hopefully we can get some hint there

**Comment by mjthoraval** [comment]
Done, thank you.

**Comment by retorquere** [comment]
Can you serialize the container of that element after that happens? I can indeed reproduce it at will, but even if I remove all my code that scribbles in that area, the problem remains.

**Comment by retorquere** [comment]
Oh and it'd be helpful if you could add a mutationobserver to log when it is removed (or hidden?). Maybe what BBT is doing around that point will give us some idea.

**Comment by windingwind** [comment]
Hmm... I am using `Zotero.Reader.registerEventListener("renderToolbar", callback)` API to create a button in the reader's toolbar, which I guess is...not possibly be broken by BBT or any plugin.

Try the build below: I've added an IntersectionObserver and when the element becomes visible/invisible it will console.log and Zotero.debug `reader menu button is (in)visible` with the element's parent element. Please let me know if there's more I can help.

[zotero-actions-tags.xpi.zip](https://github.com/windingwind/zotero-actions-tags/files/13828190/zotero-actions-tags.xpi.zip)

**Comment by windingwind** [comment]
The relevant code is here, in case you need it:

https://github.com/windingwind/zotero-actions-tags/blob/d887e23dd3b512f75d7ac4d3e7f3de6f490c1d7b/src/modules/menu.ts#L78-L152

**Comment by retorquere** [comment]
I have no idea how Zotero.Reader works or how BBT could interfere with it; BBT is not using it. I have replayed the scenario and `reader menu button is visible` doesn't show up at all in the log after start. It isn't until the tab is closed and reopened that the message appears. If I disable all UI code from BBT entirely, the problem still occurs. Can you put a log statement at the top of your "renderToolbar" listener to verify it isn't being called?

**Comment by windingwind** [comment]
OK, now it shows a log `reader renderToolbar called` with the callback args. 

Could BBT somehow delay or affect the event dispatch on readers?

[zotero-actions-tags.xpi.zip](https://github.com/windingwind/zotero-actions-tags/files/13829533/zotero-actions-tags.xpi.zip)

**Comment by retorquere** [comment]
I have no idea how it would do that. And then why doesn't that happen on re-open?

Do I understand correctly that [this](https://github.com/windingwind/zotero-actions-tags/blob/d887e23dd3b512f75d7ac4d3e7f3de6f490c1d7b/src/modules/menu.ts#L106) is reached correctly then? What point in the code is not being reached?

**Comment by windingwind** [comment]
OK... I guess perhaps BBT loading somehow delays the loading of other plugins and thus the registration of these callbacks comes after Zotero opens the readers. So this isn't actually a bug with BBT. I'll try to release a fix.

**Comment by mjthoraval** [comment]
I have updated BBT to v6.7.143. Then I have tested to see if the problem was still there. But I could not reproduce anymore...
Then I went back to v6.7.140 to double check that the problem was fixed by the update. But I still could not reproduce anymore with exactly the same configuration as before...

Are you both able to reproduce?
Also with v6.7.143?
Any idea on what could have changed and how I could trigger the problem again to understand it?
The steps to reproduce are really simple, and you confirmed that you could reproduce, so it is not only something wrong on my side...

**Comment by retorquere** [comment]
If it's indeed a timing issue it could well be that the installation order plays a role.

**Comment by mjthoraval** [comment]
Exactly!
I have reinstalled A&T and got the problem again.
So the installation order in Zotero is actually important... Is that something normal?

**Comment by mjthoraval** [comment]
Is there any way to overwrite the order imposed by the installation order?

**Comment by retorquere** [comment]
> Exactly!
> I have reinstalled A&T and got the problem again.
> So the installation order in Zotero is actually important... Is that something normal?

I think it's not entirely avoidable given how bootstrapped plugins work.

**Comment by retorquere** [comment]
> Is there any way to overwrite the order imposed by the installation order?

Probably, yes, but that's just kicking the problem down the road.

**Comment by windingwind** [comment]
OK I've released a new beta, hope it works

**Comment by windingwind** [comment]
Not sure but this could be possibly fixed in the Zotero side's API. I will notify the team

**Comment by mjthoraval** [comment]
I confirm that it is fixed.
Thank you very much both of you!
